# Default values for changelog-frontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: irori.johansson.tech/automation-liberation/changelog-frontend
  tag: latest
  pullPolicy: Always

imagePullSecrets:
  - name: docker-registry-credentials
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  servicePort: 80
  targetPort: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/cluster-issuer: letsencrypt-productions
  hosts:
    - host: changelog.johansson.tech
      paths:
        - /

  tls:
    - secretName: changelog-johansson-tech
      hosts:
        - changelog.johansson.tech

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
